Repository anchore/scan-action, pull requests merged in 2024-10, with the labels that each got.

#348 chore: short-lived grype-db cache
  .gitattributes
  .github/workflows/dependabot-build.yml
  .github/workflows/test.yml
  README.md
  action.yml
  dist/index.js
  dos2unix.js
  download-grype/action.yml
  index.js
  jest.config.js
  package-lock.json
  package.json
  tests/action.test.js
  tests/action_args.test.js
  tests/db_server.js
  tests/dist.test.js
  tests/fixtures/content-merge.fixture.json
  tests/fixtures/policy_evaluation.fixture.json
  tests/grype_command.test.js
  tests/index.test.js
  tests/mocks.js
Labels: enhancement, major

#387 chore: add changelog ignore
  .github/release-drafter.yml
Labels: changelog-ignore

#388 Add release docs
  RELEASE.md
Labels: dependencies
